### ISSUE TITLE
Why promises are not native?

### ISSUE THREAD

**Issue by Globik** [raptorjs/raptor-promises#1]
Why raptor-promises is not using the native Promises out from the box with node=>4.0. Why are you using q?

**Comment by patrick-steele-idem** [comment]
Fair question...this module was created before native promises existed was meant as a lightweight wrapper around various promise implementations. Also, the `q` library is not a hard dependency so it will not be pulled in automatically if this module is used in the browser. This module should be deprecated now that native promises are available and can easily be polyfilled. I hope that answers your question. Feel free to reopen if not :)
